use utoipa::OpenApi;

// These are generated by #[utoipa::path(...)]
use crate::routes::ai::__path_detect_intent;
use crate::routes::health::__path_health_check;

use crate::models::intent::{IntentRequest, IntentResponse};

#[derive(OpenApi)]
#[openapi(
    paths(
        health_check,
        detect_intent
    ),
    components(
        schemas(IntentRequest, IntentResponse)
    ),
    tags(
        (name = "Health", description = "Backend health check endpoints"),
        (name = "BuildX AI", description = "AI planning endpoints for BuildX")
    )
)]
pub struct ApiDoc;